const data = [
  {
    id: 1,
    imgUrl: "dex-ezekiel-WlHGsh3Ig0E-unsplash.jpg",
    alt: "Primera experiencia",
    average: 5.0,
    reviews: 6,
    country: "USA",
    description: "Life lessons with Linus Trovalds",
    price: 136,
    location: "Online",
    isAvailable: false,
  },
  {
    id: 2,
    imgUrl: "giordano-rossoni-sx1f8vqTsu8-unsplash.jpg",
    alt: "Second experience",
    average: 5.0,
    reviews: 18,
    country: "USA",
    description: "Life lessons with Linus Trovalds",
    price: 95,
    location: "Online",
    isAvailable: true,
  },
  {
    id: 3,
    imgUrl: "imattsmart-1hzWz1pOjNA-unsplash.jpg",
    alt: "Third experience",
    average: 4.8,
    reviews: 55,
    country: "USA",
    description: "Life lessons with Linus Trovalds",
    price: 136,
    location: "Online",
    isAvailable: false,
  },
  {
    id: 4,
    imgUrl: "vadim-sadovski-K7vbgdF2wMI-unsplash.jpg",
    alt: "Fourth experience",
    average: 4.5,
    reviews: 55,
    country: "USA",
    description: "Life lessons with Linus Trovalds",
    price: 136,
    location: "Online",
    isAvailable: true,
  },
];

export { data };
